version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/crp
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - crp-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_BASE_URL: http://localhost:5000/api
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - crp-network

  mongodb:
    image: mongo:7
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - crp-network

networks:
  crp-network:
    driver: bridge

volumes:
  mongo-data: